<?php

namespace ContainerDzE3333;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J3wneVMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j3wneVM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j3wneVM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'callApiService' => ['privates', 'App\\Service\\CallApiService', 'getCallApiServiceService', true],
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
        ], [
            'callApiService' => 'App\\Service\\CallApiService',
            'chartBuilder' => '?',
        ]);
    }
}
