<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDzE3333\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDzE3333/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDzE3333.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDzE3333\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDzE3333\App_KernelDevDebugContainer([
    'container.build_hash' => 'DzE3333',
    'container.build_id' => 'c56dce93',
    'container.build_time' => 1638375767,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDzE3333');
