<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxdxWKc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxdxWKc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQxdxWKc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQxdxWKc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQxdxWKc\App_KernelDevDebugContainer([
    'container.build_hash' => 'QxdxWKc',
    'container.build_id' => '63918d8a',
    'container.build_time' => 1638462127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxdxWKc');
